# Generated by Django 4.1.1 on 2022-12-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('url_image', models.TextField()),
                ('author', models.TextField()),
                ('publishedAt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('fisrt_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
